#pragma once

#include <twz/obj.h>

#define TWZSLOT_EXEC 0
#define TWZSLOT_EXEC_DATA 1

#define TWZSLOT_INTERP 2
#define TWZSLOT_INTERP_DATA 3

#define TWZSLOT_MAX_LOWMAP 0x100
#define TWZSLOT_MAX_SLOT 0x1fffful

#define TWZSLOT_THREAD_STRIDE 4

#define TWZSLOT_THREAD_OFFSET_CTRL 0
#define TWZSLOT_THREAD_OFFSET_STACK 1
#define TWZSLOT_THREAD_OFFSET_QUEUE 2
#define TWZSLOT_THREAD_OFFSET_BUFFER 3

#define TWZSLOT_THREAD_OBJ(i, o) ({ TWZSLOT_THREAD_START + ((i)*TWZSLOT_THREAD_STRIDE) + (o); })

#define TWZSLOT_CVIEW 0x1fff0ul
#define TWZSLOT_UNIX 0x1fff1ul

#define TWZSLOT_FILES_BASE 0x100
#define TWZSLOT_FILES_NUM 0xf00

#define TWZSLOT_MMAP_BASE 0x1000
#define TWZSLOT_MMAP_NUM 0x8000

#define TWZSLOT_THREAD_START 0x9000
#define TWZSLOT_THREAD_NUM ({ 0x7000 / TWZSLOT_THREAD_STRIDE; })

#define TWZSLOT_ALLOC_START 0x10000
#define TWZSLOT_ALLOC_MAX 0x1ffe0

#ifndef __KERNEL__
#define SLOT_TO_VADDR(s) ({ (void *)((s)*OBJ_MAXSIZE); })
#define VADDR_TO_SLOT(s) ({ (size_t)((uintptr_t)(s) / OBJ_MAXSIZE); })
#endif
