#pragma once
#include <stddef.h>
#include <sys/uio.h>

struct syscall_args;
long hook_fork(struct syscall_args *args);
long hook_sys_pwritev2(struct syscall_args *);
long hook_sys_pwritev(struct syscall_args *);
long hook_sys_writev(struct syscall_args *);
long hook_sys_pwrite(struct syscall_args *);
long hook_sys_write(struct syscall_args *);
long hook_sys_preadv2(struct syscall_args *);
long hook_sys_preadv(struct syscall_args *);
long hook_sys_readv(struct syscall_args *);
long hook_sys_pread(struct syscall_args *);
long hook_sys_read(struct syscall_args *);
long hook_sys_fcntl(struct syscall_args *args);
long hook_sys_fstat(struct syscall_args *args);
long hook_sys_fstatat(struct syscall_args *args);
long hook_sys_lstat(struct syscall_args *args);
long hook_sys_stat(struct syscall_args *args);
long hook_clone(struct syscall_args *);
long hook_execve(struct syscall_args *);
long hook_poll(struct syscall_args *args);
long hook_ppoll(struct syscall_args *args);
long hook_pselect(struct syscall_args *args);
long hook_select(struct syscall_args *args);
long hook_mmap(struct syscall_args *args);
long hook_mremap(struct syscall_args *args);
long hook_sigaction(struct syscall_args *args);
long hook_setrlimit(struct syscall_args *args);
long hook_getrlimit(struct syscall_args *args);
long hook_prlimit(struct syscall_args *args);
long hook_uname(struct syscall_args *args);
long hook_sys_gettid(struct syscall_args *args);
long hook_futex(struct syscall_args *args);
long hook_kill(struct syscall_args *args);
long hook_wait4(struct syscall_args *args);
long hook_wait3(struct syscall_args *args);
long hook_waitpid(struct syscall_args *args);
long hook_wait(struct syscall_args *args);
long hook_nanosleep(struct syscall_args *args);
long hook_clock_gettime(struct syscall_args *args);
long hook_open(struct syscall_args *args);
long hook_ioctl(struct syscall_args *args);
long hook_getdents(struct syscall_args *args);
long hook_faccessat(struct syscall_args *args);
long hook_access(struct syscall_args *args);
long hook_readlink(struct syscall_args *args);
long hook_dup(struct syscall_args *args);
long hook_dup2(struct syscall_args *args);
long hook_dup3(struct syscall_args *args);
long hook_proc_info_syscalls(struct syscall_args *args);
long hook_exit(struct syscall_args *args);
